<a href="https://colab.research.google.com/github/Surya7400/data-analytics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#create numpy array
import numpy as np
n=np.array([1,2,3])
print(n)
print(type(n))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#create numpy array
import numpy as np
n=np.array([1,2,3])
print(n)
print("dimension=",n.ndim)

[1 2 3]
dimension= 1


In [ ]:
#create numpy array
import numpy as np
n=np.array([[1,2,3],[4,5,6]])
print(n)
print("dimension=",n.ndim)

[[1 2 3]
 [4 5 6]]
dimension= 2


In [ ]:
#initialize numpy array
import numpy as np
n=np.zeros((2,2))
print(n)
print(type(n))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [ ]:
#create numpy array
import numpy as np
n=np.array([1,2,3])
print(n)
print(n.dtype)

[1 2 3]
int64


In [ ]:
#get the datatype of a numpy array
import numpy as np
n=np.array(['amrutha','rohit','aswin','virat'])
print(n.dtype)

<U7


In [ ]:
#convert one datatype to another
import numpy as np
n=np.array(['10','20','30','40','50'])
print(n)
print(n.dtype)
n2=n.astype('i')
print(n2)
print(n2.dtype)

['10' '20' '30' '40' '50']
<U2
[10 20 30 40 50]
int32


In [ ]:
#access the 1st element in
import numpy as np
n=np.array([1,2,3])
print(n)
print(n.dtype)